#!/bin/bash
# Quick deployment script for Render

echo "🚀 Deploying Expense Tracker to Render"
echo "======================================"
echo ""
echo "Steps to deploy:"
echo ""
echo "1. Ensure project is in a GitHub repository"
echo "   - Create repo on GitHub"
echo "   - Push this code: git push"
echo ""
echo "2. Go to https://render.com"
echo "   - Sign in with GitHub"
echo "   - Click 'New +' → 'Blueprint'"
echo "   - Select your expense-tracker repository"
echo "   - Render will auto-detect render.yaml"
echo "   - Click 'Create'"
echo ""
echo "3. Wait for deployment (5-10 minutes)"
echo ""
echo "4. Your Render Links:"
echo "   - Backend API: https://expense-tracker-backend-[id].onrender.com"
echo "   - (Optional) Frontend: Deploy to Cloudflare Pages or use same domain"
echo ""
echo "5. Update Frontend API URL"
echo "   - In Cloudflare Pages, set environment variable:"
echo "   - REACT_APP_API_URL=https://your-backend-url.onrender.com"
echo ""
echo "=============================="
